apiVersion: v1
kind: Service
metadata:
   name: transporter-manager
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-port
  selector:
    app: transporter-manager
