apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: v2f-aws-to-gcp-agent
spec:
  replicas: 16
  template:
    metadata:
      labels:
        app: v2f-aws-to-gcp-agent
    spec:
      serviceAccountName: v2f-aws-to-gcp-agent-sa
      initContainers:
        - name: transporter-aws-to-gcp-agent-config
          image: us.gcr.io/broad-dsp-monster-dev/transporter-aws-to-gcp-agent-config:b4d0078
          imagePullPolicy: Always
          env:
            - name: AWS_SECRETS_PATH  
              value: /secret/dsde/monster/dev/transporter/agents/v2f/aws
            - name: GCS_WRITER_SECRETS_PATH  
              value: /secret/dsde/monster/dev/transporter/agents/v2f/writer-sa.json
            - name: VAULT_TOKEN_FILE
              value: /etc/vault/token
          volumeMounts:
            - name: token
              mountPath: /etc/vault
            - name: appdir
              mountPath: /working
      containers:
        - name: v2f-aws-to-gcp-agent
          image: broadinstitute/transporter-aws-to-gcp-agent:8823f590e7b3259e1751aff0a7b0c4850e953efb
          imagePullPolicy: Always
          command: [ "/bin/bash", "/etc/entrypoint.sh" ]
          env:
            - name: AGENT_HEAP_SIZE
              value: 512m
          lifecycle:
            preStop:
              exec:
                # Give the app the chance to finish any in-flight transfer.
                command: ["sh", "-ce", "kill -s TERM 1; while $(kill -0 1 2>/dev/null); do sleep 1; done"]
          resources:
            requests:
              cpu: 1000m
              memory: 800Mi
            limits:
              memory: 832Mi
          volumeMounts:
            - name: appdir
              mountPath: /etc/application.conf
              subPath: transporter-aws-to-gcp-agent/application.conf
              readOnly: true
            - name: appdir
              mountPath: /etc/entrypoint.sh
              subPath: transporter-aws-to-gcp-agent/entrypoint.sh
            - name: appdir
              mountPath: /secrets/gcs/credentials.json
              subPath: transporter-aws-to-gcp-agent/gcs-writer-sa.json
      volumes:
        - name: token
          secret:
            secretName: vault-token
            items:
              - key: token
                path: token
                mode: 0444
        - name: appdir
          emptyDir: {}
