apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingest-cluster-entity-operator-use-psp
  labels:
    app: strimzi
subjects:
- kind: ServiceAccount
  name: ingest-cluster-entity-operator
roleRef:
  kind: Role
  name: use-pod-security-policy-role
  apiGroup: rbac.authorization.k8s.io
