FROM broadinstitute/configurator-base:1.0.2

COPY transporter-manager /configs/transporter-manager/
COPY transporter-manager-migrations /configs/transporter-manager-migrations/

CMD /usr/local/bin/cp-config.sh
