#!/usr/bin/env bash
set -euo pipefail

declare -r SCRIPT_DIR=$(cd $(dirname $0) && pwd)
declare -r PROJECT_DIR=$(dirname ${SCRIPT_DIR})

declare -ra INIT_CONTAINER_SERVICES=(cloudsql-proxy)
declare -r INIT_CONTAINER_PREFIX=us.gcr.io/broad-dsp-gcr-public

function build_and_push () {
    local -r service_name=$1 version=$2
    local -r service_dir=${PROJECT_DIR}/init-containers/${service_name}
    local -r service_tag="${INIT_CONTAINER_PREFIX}/${service_name}-config:${version}"

    docker build -t ${service_tag} ${service_dir}
    docker push ${service_tag}
}

function main () {
    # Init containers should use first 7 chars of git hash for their tag.
    # https://github.com/broadinstitute/dsp-k8s-deploy/blob/master/adding-a-service.md#building-and-pushing-init-container-images
    local -r version=$(git rev-parse HEAD | cut -c 1-7)

    for service_name in ${INIT_CONTAINER_SERVICES[@]}; do
        build_and_push ${service_name} ${version}
    done
}

main
