#!/usr/bin/env bash
set -euo pipefail

declare -r SCRIPT_DIR=$(cd $(dirname $0) && pwd)
declare -r PROJECT_DIR=$(cd $(dirname ${SCRIPT_DIR}) && pwd)

declare -r STRIMZI_PROFILE=${PROJECT_DIR}/profiles/strimzi/k8s

function check_usage () {
    if [ $# -ne 1 ]; then
        2>&1 echo "Usage: $0 <strimzi-release-tag>"
        exit 1
    fi
}

function download_release () {
    local -r version=$1 output=$2
    local -r uri="https://github.com/strimzi/strimzi-kafka-operator/releases/download/${version}/strimzi-${version}.tar.gz"

    mkdir -p ${output}
    curl -sL ${uri} | tar xzf - --directory ${output} --strip-components 2 strimzi-${version}/install
}

function templatize_configs () {
    local -r config_dir=$1
    local -ra to_templatize=( $(find ${config_dir} -name '*.yaml' -exec  grep -r -l 'namespace: ' {} \;) )

    for config in ${to_templatize[@]}; do
        sed 's/namespace: .*/namespace: {{env "OWNER"}}/g' ${config} > ${config}.ctmpl
        rm ${config}
    done
}

function main () {
    check_usage ${@}

    local -r strimzi_version=$1

    2>&1 echo Downloading strimzi release ${strimzi_version} to ${STRIMZI_PROFILE}...
    download_release ${strimzi_version} ${STRIMZI_PROFILE}

    2>&1 echo Template-izing downloaded configs...
    templatize_configs ${STRIMZI_PROFILE}
}

main ${@}
