#!/usr/bin/env bash
set -euo pipefail

declare -r SCRIPT_DIR=$(cd $(dirname $0) && pwd)
declare -r PROJECT_DIR=$(cd $(dirname ${SCRIPT_DIR}) && pwd)

function check_usage () {
    if [ $# -ne 2 ]; then
        2>&1 echo "Usage: $0 <strimzi-release-tag> <output-dir>"
        exit 1
    fi
}

function download_release () {
    local -r version=$1 output=$2
    local -r uri="https://github.com/strimzi/strimzi-kafka-operator/releases/download/${version}/strimzi-${version}.tar.gz"

    mkdir -p ${output}
    curl -sL ${uri} | tar xzf - --directory ${output} --strip-components 3 strimzi-${version}/install/cluster-operator
}

function templatize_configs () {
    local -r config_dir=$1
    local -ra to_templatize=( $(find ${config_dir} -name '*.yaml' -exec  grep -r -l 'namespace: ' {} \;) )

    for config in ${to_templatize[@]}; do
        sed 's/namespace: .*/namespace: {{env "K8S_NAMESPACE"}}/g' ${config} > ${config}.ctmpl
        rm ${config}
    done
}

function main () {
    check_usage ${@}

    local -r strimzi_version=$1
    local -r output_dir=$2

    2>&1 echo Downloading strimzi release ${strimzi_version} to ${output_dir}...
    download_release ${strimzi_version} ${output_dir}

    2>&1 echo Template-izing downloaded configs...
    templatize_configs ${output_dir}
}

main ${@}
