apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: ingest-cluster
spec:
  kafka:
    version: 2.2.1
    replicas: 3
    listeners:
      tls:
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        class: kafka-storage
        deleteClaim: false
    resources:
      requests:
        cpu: 1000m
        memory: 3Gi
      limits:
        cpu: 2000m
        memory: 4Gi
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      class: zookeeper-storage
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
