apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-schema
data:
  schema.conf: |-
    org.broadinstitute.transporter.transfer.schema: {
      "$schema": "http://json-schema.org/draft-04/schema",
      "type": "object",
      "properties": {
        "s3Bucket": { "type": "string" },
        "s3Region": { "type":  "string" },
        "s3Path": { "type": "string" },
        "gcsBucket": { "type": "string" },
        "gcsPath": { "type": "string" },
        "expectedSize": { "type": "integer" },
        "expectedMd5": { "type": "string", "pattern": "[0-9a-f]+" },
        "force": { "type":  "boolean" }
      },
      "required": ["s3Bucket", "s3Region", "s3Path", "gcsBucket", "gcsPath"],
      "additionalProperties": false
    }
